## Logistic regression of movie reviews


In [136]:
import pandas as pd
address="C:/Users/ANTHONY/Desktop/CSV&XLSX/Movie_review_sample.xlsx"
movies = pd.read_excel(address)
movies

review     label
0    One of the other reviewers has mentioned that ...  positive
1    A wonderful little production. <br /><br />The...  positive
2    I thought this was a wonderful way to spend ti...  positive
3    Basically there's a family where a little boy ...  negative
4    Petter Mattei's "Love in the Time of Money" is...  positive
..                                                 ...       ...
520  I am a huge fan of the Farcry Game, HUGE fan. ...  negative
521  one of the best ensemble acted films I've ever...  positive
522  I haven't seen this movie in about 5 years, bu...  positive
523  Today, I wrote this review in anger at Uwe Bol...  negative
524  You cannot deny that we have an affinity for s...  negative

[525 rows x 2 columns]

In [137]:
num=[]
for i in movies.label:
    if i=="positive":
        num.append(1)
    else:
        num.append(0)

movies['labell']=num
movies

review     label  labell
0    One of the other reviewers has mentioned that ...  positive       1
1    A wonderful little production. <br /><br />The...  positive       1
2    I thought this was a wonderful way to spend ti...  positive       1
3    Basically there's a family where a little boy ...  negative       0
4    Petter Mattei's "Love in the Time of Money" is...  positive       1
..                                                 ...       ...     ...
520  I am a huge fan of the Farcry Game, HUGE fan. ...  negative       0
521  one of the best ensemble acted films I've ever...  positive       1
522  I haven't seen this movie in about 5 years, bu...  positive       1
523  Today, I wrote this review in anger at Uwe Bol...  negative       0
524  You cannot deny that we have an affinity for s...  negative       0

[525 rows x 3 columns]

### conversion to word vector

In [138]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
import numpy as np

# Create a series to store the labels: y
y = movies.label

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(movies['review'], y, test_size=0.33, random_state=53)  #he function will take 33% of rows to be marked as test data, and remove them from the training data.

# Initialize a CountVectorizer object: ...... Next, we create a countvectorizer which turns my reviews into BAG OF WORDS vectors similar to a Gensim corpus, 
count_vectorizer = CountVectorizer()
print(count_vectorizer)   

# Transform the training data using only the 'text' column values: count_train ......this fitting to model is to convert it to numerical words vector
count_train = count_vectorizer.fit_transform(X_train)     #this is to fit into LOR model and make it a sparse matrix

#needs a feature vector with the same number of dimensions as count_train.
#You have to transform the test string to a feature vector
#using the same vectorizer instance, before you feed it to the MODEL LOG REGRESS....

# Transform the test data using only the 'text' column values: count_test 
count_test = count_vectorizer.transform(X_test)           #this is to predict the value of fitted model

#this is to test with a single string
review_=['Mohanlal is yet again a revelation in Drishyam 2. In the film, especially during emotional sequences where the actor’s eyes are moist with tears, Mohanlal is just excellent. Even though the supporting characters had relevance, Drishyam 2 is all about Mohanlal and rightly so.Throughout the film, we get some deja vu moments, like in the climax or where Varun’s father pleads with Georgekutty to reveal the crucial information. ']
review__testing=count_vectorizer.transform(review_)

# Print the first 10 features of the count_vectorizer
print(count_vectorizer.get_feature_names()[:10])
print(count_train.toarray())   #to convert sparse matrix to array
count_train
count_test
review__testing

CountVectorizer()
['00', '000', '007', '08', '10', '100', '1000', '101', '105', '11']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<1x10467 sparse matrix of type '<class 'numpy.int64'>'
	with 41 stored elements in Compressed Sparse Row format>

### USING LOR MODEL

In [142]:
# Import the logistic regression
from sklearn.linear_model import LogisticRegression

# Build a logistic regression model and calculate the accuracy
log_reg = LogisticRegression().fit(count_train, y_train)
print('Accuracy of logistic regression: trains set', log_reg.score(count_train, y_train))

Accuracy of logistic regression: trains set 1.0


C:\Users\ANTHONY\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [143]:
# Create the predicted tags: pred
pred = log_reg.predict(count_test)
print(pred)
print('Accuracy of logistic regression: TEST set', log_reg.score(count_test, y_test))


['positive' 'negative' 'positive' 'negative' 'negative' 'positive'
 'negative' 'positive' 'negative' 'negative' 'negative' 'positive'
 'negative' 'negative' 'positive' 'positive' 'positive' 'positive'
 'negative' 'positive' 'negative' 'positive' 'negative' 'negative'
 'positive' 'positive' 'positive' 'positive' 'positive' 'negative'
 'negative' 'positive' 'positive' 'negative' 'negative' 'positive'
 'positive' 'positive' 'negative' 'negative' 'negative' 'negative'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'positive' 'negative' 'positive' 'positive' 'negative' 'negative'
 'negative' 'negative' 'negative' 'positive' 'negative' 'positive'
 'negative' 'positive' 'positive' 'positive' 'negative' 'negative'
 'negative' 'positive' 'positive' 'positive' 'negative' 'negative'
 'positive' 'negative' 'positive' 'negative' 'positive' 'positive'
 'negative' 'positive' 'positive' 'negative' 'negative' 'positive'
 'negative' 'positive' 'positive' 'positive' 'positive' 'posit

### Product reviews with regularization
In this exercise, you will work once more with the reviews dataset of Amazon product reviews. A vector of labels y contains the sentiment : 1 if positive and 0 otherwise. The matrix X contains all numeric features created using a BOW approach.

You will need to train two logistic regression models with different levels of regularization and compare how they perform on the test data. Remember that regularization is a way to control the complexity of the model. The more regularized a model is, the less flexible it is but the better it can generalize. Models with higher level of regularization are often less accurate than non-regularized ones.

In [144]:
# Train a logistic regression with regularization of 1000
log_reg1 = LogisticRegression(C=1000).fit(count_train, y_train)
# Train a logistic regression with regularization of 0.001
log_reg2 = LogisticRegression(C=0.001).fit(count_train, y_train)

# Print the accuracies
print('Accuracy of model 1: ', log_reg1.score(count_test, y_test))
print('Accuracy of model 2: ', log_reg2.score(count_test, y_test))

Accuracy of model 1:  0.7241379310344828
Accuracy of model 2:  0.6379310344827587


C:\Users\ANTHONY\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#### TESTING WITH MY OWN SET OF REVIEW

In [130]:
pred2 = log_reg.predict(review__testing)
print(pred2)

['positive']


TESTING WITH ANOTHER SET OF REVIEWS

In [132]:
review2=['In this franchise reboot, the writer-director Elizabeth Banks tries to sell stale goods with a sheen of empowerment.','a big, brashly beautiful, grandiosely enjoyable one that will provide succor to audiences long-starved for escapist spectacle on this beefy, made-for-Imax scale.']
review_test_2=count_vectorizer.transform(review2)
review_test_2

<2x10467 sparse matrix of type '<class 'numpy.int64'>'
	with 32 stored elements in Compressed Sparse Row format>

In [133]:
pred3 = log_reg.predict(review_test_2)
print(pred3)

['negative' 'positive']


### CONFUSION MATRIX

In [148]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [149]:
#confusion matrix
# Print the performance metrics
print('Accuracy score test set: ', accuracy_score(y_test, pred))
print('Confusion matrix test set: \n', confusion_matrix(y_test, pred)/len(y_test))

Accuracy score test set:  0.7298850574712644
Confusion matrix test set: 
 [[0.35632184 0.15517241]
 [0.11494253 0.37356322]]


#### Predict probabilities of movie reviews


In [151]:
# Train a logistic regression
log_reg = LogisticRegression().fit(X_train, y_train)

# Predict the probability of the 0 class
prob_0 = log_reg.predict_proba(X_test)[:, 0]
# Predict the probability of the 1 class
prob_1 = log_reg.predict_proba(X_test)[:, 1]

print("First 10 predicted probabilities of class 0: ", prob_0[:10])
print("First 10 predicted probabilities of class 1: ", prob_1[:10])

ValueError: could not convert string to float: 'Despite later claims, this early-talkie melodrama has very little in common with "Citizen Kane": It\'s a biopic of a ruthless but human fictional plutocrat, told in flashback but hopping around time. The scriptwriter, Preston Sturges, shows none of his later gift for sparkling dialog, and none of the myriad cinematic innovations of "Kane" are evident. Still, it\'s very watchable, with a young Spencer Tracy (his old-man makeup makes him look just like, well, an old Spencer Tracy) showing depth and authority, and Colleen Moore -- a little past her prime, and not physically well matched -- playing a multifaceted woman-behind-the-man. There\'s also Helen Vinson as one of the most treacherous femmes fatales in movie history, sending the final third into ecstatic soap-opera reverberations. The surviving print is jumpy and has missing audio snippets, and there are some plot holes left open (how would she know whose son it was if she\'s sleeping with both of them?), and the music is awfully hokey. For all that, I was quite fascinated.'